services:
  mc:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      VERSION: "1.20.1"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/simplecolonies"
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: "6144M"
      MOTD: "Serveur Obv1ous - MineColonies+"
      ICON: https://raw.githubusercontent.com/cprodhomme/obv1ous/refs/heads/develop/app/assets/images/team-ico/black.png
      USE_AIKAR_FLAGS: "true"
      TZ: "Europe/Paris"
      DIFFICULTY: "3"
      ENABLE_COMMAND_BLOCK: "true"
      OPS: |-
        Cle_61
      ENABLE_WHITELIST: "true"
      WHITELIST: |-
        Cle_61
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 25575
      RCON_CMDS_STARTUP:  |-
        gamerule doFireTick false
        gamerule playersSleepingPercentage 60
    volumes:
      - "./data:/data"

  mc-backup:
    image: itzg/mc-backup
    container_name: mc-backup
    environment:
      BACKUP_METHOD: rclone
      RCLONE_REMOTE: hetzner
      RCLONE_DEST_DIR: minecolonies

      RCLONE_CONFIG_HETZNER_TYPE: s3
      RCLONE_CONFIG_HETZNER_PROVIDER: Other
      RCLONE_CONFIG_HETZNER_ACCESS_KEY_ID: ${RCLONE_CONFIG_HETZNER_ACCESS_KEY_ID}
      RCLONE_CONFIG_HETZNER_SECRET_ACCESS_KEY: ${RCLONE_CONFIG_HETZNER_SECRET_ACCESS_KEY}
      RCLONE_CONFIG_HETZNER_ENDPOINT: ${RCLONE_CONFIG_HETZNER_ENDPOINT}
      RCLONE_CONFIG_HETZNER_REGION: ${RCLONE_CONFIG_HETZNER_REGION}

      INITIAL_DELAY: 2m
      BACKUP_INTERVAL: 24h
      PRUNE_BACKUPS_DAYS: 7

      RCON_HOST: mc
      RCON_PORT: 25575
      RCON_PASSWORD: ${RCON_PASSWORD}

    volumes:
      - ./data:/data:ro
      - ./backups:/backups
      - ./rclone.config:/config/rclone/rclone.conf:ro

volumes:
  rclone-config:
    external: true
